### PR TITLE
Support Python 3.12

### LINKED ISSUE #6460: Support Python 3.12
**Description of the issue**

The current development requirements in [dev_tools/requirements/dev.env.txt](https://github.com/quantumlib/Cirq/blob/c3de7064224b8c2aec91646e83184b03b35b2010/dev_tools/requirements/dev.env.txt#L1) do not work, because [pylatex~=1.3.0](https://github.com/quantumlib/Cirq/blob/c3de7064224b8c2aec91646e83184b03b35b2010/cirq-core/cirq/contrib/requirements.txt#L4) does not install on Python 3.12.1.  There may be possibly more incompatible packages which were enqueued for installation after pylatex.

```
$ pip3.12 install "pylatex~=1.3.0"
...
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
```

**Cirq version**

1.4.0.dev at c3de7064224b8c2aec91646e83184b03b35b2010

### PR DESCRIPTION
**Pull request by pavoljuhas**
- Fix attribute error in `engine_test.py::test_create_context`
- Adjust package presence assertion in `test_isolated_env_cloning`
- Bump up to virtualenv>=20.23, filelock~=3.1, pylatex~=1.4
- Bump up to grpcio-tools~=1.59.0 and recompile protos
- Relax qiskit-aer requirement to qiskit-aer~=0.12.0.  Allow qiskit-aer-0.12.0
  which has source archive on PyPI and can be installed for Python 3.12.
- Bump up to quimb~=1.7 which installs correctly with Python 3.12
  Remove quimb-only dependencies from our requirements, let
  quimb sort out its dependencies itself.
- CI - add pytest jobs with Python 3.12
- Skip mysteriously failing test of Contract-a-Grid-Circuit.ipynb

Fixes #6460

### CODE REVIEW

**Comment by migueltorrescosta** [comment]
Thank you @pavoljuhas for working on making Cirq Python 3.12 compatible. I see that some packages were bumped in order for tests to pass. Is there a policy for updating `Cirq` dependencies? For example,
- I use [poetry](https://python-poetry.org/) to manage my packages, which makes updating to the latest version feasible by the command `poetry update`.
- [Dependabot](https://github.com/dependabot) and [Renovate](https://github.com/renovatebot/renovate) do this too, as bot contributors to the repo ( i.e. they create their own PRs whenever an update is possible )

**Comment by pavoljuhas** [comment]
> Thank you @pavoljuhas for working on making Cirq Python 3.12 compatible. I see that some packages were bumped in order for tests to pass. Is there a policy for updating `Cirq` dependencies? For example,
> 
> * I use [poetry](https://python-poetry.org/) to manage my packages, which makes updating to the latest version feasible by the command `poetry update`.
> * [Dependabot](https://github.com/dependabot) and [Renovate](https://github.com/renovatebot/renovate) do this too, as bot contributors to the repo ( i.e. they create their own PRs whenever an update is possible )

Thank you for your comment.  In general we try to follow the [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) version policy for Python and NumPy.  As for other packages, we seek to use loose version specifications, e.g., `somepackage~=1.2` to freeze the major version but match recent minor releases which in theory should have compatible APIs.  Cirq is often used as a library that should be installable with other projects so we do not want to restrict its dependency specifications more than needed.  If there is a breaking change for some third-party release, we add an upper bound for the last working version.  These rules have a tendency to get outdated, which is a part of the process that could be improved.
We revisit dependencies at the release time or when there is a need for major-version upgrade of some package.

In regards to the poetry, the `poetry update` creates a lock file with exact versions of all direct and transitive dependencies at the time of execution - which is useful for reproducible installations.  The lock files are resolved from package version constrains in pyproject.toml which need [manual updates](https://python-poetry.org/docs/cli/#update) so that part of labor seems to be the same.

It would be nice to get notifications when our requirement specs exclude the latest stable releases.
We are glad to consider suggestions if you (or others) know of such tool.

**Review by NoureldinYosri — APPROVED** [review]
thanks for the great job @pavoljuhas

**Comment by migueltorrescosta** [comment]
Thank you for the thorough answer @pavoljuhas. My suggested approach would be either Dependabot or Renovate, as they generate small PRs which only update the relevant versions, making it easier to approve/reject version bumps. Usually it's nice to limit these to major versions, otherwise we get flooded with these PRs, and as maintainers there are more important things you can focus on :) I'd recommend:

1. Creating an issue to automatise version updates through Dependabot / Renovate / maybe even snyk for vulnerability detection, so that maintainers don't have to spend time on it when needed. It is not urgent, so it would probably sit in the backlog until someone wants to take this work, as it should.
2. Merging this PR as is. It is independent of the above

Do you want me to create the issue?
