### ISSUE TITLE
cirq no longer has a __version__ attribute (if you upgrade from 0.10.0)

### ISSUE THREAD

**Issue by dkafri** [quantumlib/Cirq#4115]
**Description of the issue**
I did pip install --upgrade cirq to upgrade to version 0.11.0
I noticed that cirq no longer has a __version__ attribute

**Cirq version**

This is the terminal command *suggested by this issue template*
```
python -c 'import cirq; print(cirq.__version__)'
```
It returns
```
AttributeError: module 'cirq' has no attribute '__version__'
```

**Comment by dkafri** [comment]
Note, this is not reproduced if you make a "clean install" of cirq. To get this issue it seems I have to do
```bash
pip install cirq==0.10.0
pip install --upgrade cirq
```

**Comment by maffoo** [comment]
I think this is working as expected, but we should document somewhere that when upgrading from cirq 0.10 to 0.11+ you should first `pip uninstall cirq` or start over in a fresh virtualenv.

**Comment by balopat** [comment]
Sorry for the confusion. Yes, I can add this to the release notes of v0.11.

**Comment by balopat** [comment]
Added this to the release notes + sent an email to cirq-announce. Thank you @dkafri for opening the issue!
